controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
home:
    path: /
    controller: App\Controller\MainController::index

register:
     path: /register
     controller: App\Controller\RegistrationController::register

todo:
     path: /todo
     controller: App\Controller\TaskController::new

suc:
    path: /success
    controller: App\Controller\TaskController::suc

anz:
    path: /posts
    controller: App\Controller\TaskController::show

delete_task:
    path: /delete-task/{id}
    controller: App\Controller\TaskController::deleteTask
    methods: DELETE

mail:
    path: /mail
    controller: App\Controller\MailerController::sendMail

app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: POST

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
