controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
home:
    path: /
    controller: App\Controller\MainController::index

login:
     path: /login
     controller: App\Controller\MainController::login

register:
     path: /register
     controller: App\Controller\MainController::register

todo:
     path: /todo
     controller: App\Controller\TaskController::new

suc:
    path: /success
    controller: App\Controller\TaskController::suc